#ifndef __GST_CAFFELUGIN_H__
#define __GST_CAFFELUGIN_H__

#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>

/* Open CV headers */
#include <opencv2/opencv.hpp>
#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"

#include "deepsortplugin_lib.h"

#define PACKAGE "deepsort"
#define VERSION "1.0"
#define LICENSE "LGPL"
#define DESCRIPTION "Plugin using Deep SORT Tracking"
#define BINARY_PACKAGE "Get object detection details from separate engine and track"
#define URL "https://github.com/jayveeangeles/gst-deepsort.git"

G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstDeepSortPlugin GstDeepSortPlugin;
typedef struct _GstDeepSortPluginClass GstDeepSortPluginClass;

/* Standard boilerplate stuff */
#define GST_TYPE_DEEPSORTPLUGIN (gst_deepsortplugin_get_type())
#define GST_DEEPSORTPLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), GST_TYPE_DEEPSORTPLUGIN, GstDeepSortPlugin))
#define GST_DEEPSORTPLUGIN_CLASS(klass)                                                                \
    (G_TYPE_CHECK_CLASS_CAST((klass), GST_TYPE_DEEPSORTPLUGIN, GstDeepSortPluginClass))
#define GST_DEEPSORTPLUGIN_GET_CLASS(obj)                                                              \
    (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_DEEPSORTPLUGIN, GstDeepSortPluginClass))
#define GST_IS_CAFFEPLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), GST_TYPE_DEEPSORTPLUGIN))
#define GST_IS_CAFFEPLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), GST_TYPE_DEEPSORTPLUGIN))
#define GST_DEEPSORTPLUGIN_CAST(obj) ((GstDeepSortPlugin*) (obj))

struct _GstDeepSortPlugin
{
  GstBaseTransform base_trans;

  // Context of the custom algorithm library
  DeepSortPluginCtx *deepsortpluginlib_ctx;

  // Unique ID of the element. The labels generated by the element will be
  // updated at index `unique_id` of attr_info array in NvDsObjectParams.
  guint unique_id;

  // Frame number of the current input buffer
  guint64 frame_num;

  // Input video info (resolution, color format, framerate, etc)
  GstVideoInfo video_info;

  guint max_alive;

  gfloat cos_dist;
  gfloat iou_dist;

  gchar* to_track;
  gchar* frozen_model;

  gboolean draw_results;
  guint skip_interval;
  gint max_since_update;

  Stopwatch timer;
  double convert_time = 0.0f, infer_time = 0.0f, predict_time=0.0f;
};

// Boiler plate stuff
struct _GstDeepSortPluginClass
{
  GstBaseTransformClass parent_class;
};

GType gst_deepsortplugin_get_type (void);

G_END_DECLS
#endif /* __GST_CAFFELUGIN_H__ */
